# Generated by Django 4.2.7 on 2023-11-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='telegram_chat_id'),
        ),
    ]
